# Generated by Django 5.0.7 on 2024-07-29 06:18

import django.db.models.deletion
import test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=test_app.models.get_default_author, on_delete=django.db.models.deletion.CASCADE, to='test_app.author'),
        ),
    ]
